services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "5004:3000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - mobility-network
    environment:
      - GF_SECURITY_ADMIN_USER=mobilityuser
      - GF_SECURITY_ADMIN_PASSWORD=mobilitypass
      - TZ=Etc/UTC
    deploy:
      resources:
        limits:
          memory: 2g

volumes:
  grafana:
    driver: local

networks:
  mobility-network:
    driver: bridge
    external: true
