{
 "title": "[GENERAL] Network Descriptions",
 "time": { "from": "2023-03-31T22:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cities",
    "label": "City",
    "query": "select distinct  network_name_lend::text from weekly_trips_agg wta;"
   }
  ]
 },
 "panels": [
  {
   "title": "Statistics ($cities City Level)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "cities"
  },
  {
   "title": "Total Trips",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Trips" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(trip_count) AS total_trips\r\nFROM weekly_trips_agg wta \r\nwhere network_name_lend::text IN ($cities)\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Total Returns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Returns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(total_returns) AS total_trips\r\nFROM weekly_demand_agg wda \r\nwhere network_name::text IN ($cities)"
    }
   ]
  },
  {
   "title": "Trip Durations ($cities)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  duration_minutes,\r\n  network_name_lend::text AS network_suffix\r\nFROM (\r\n  SELECT\r\n    FLOOR(EXTRACT(EPOCH FROM AGE(timestamp_return, timestamp_lend)) / 60) AS duration_minutes,\r\n    network_name_lend\r\n  FROM trips\r\n  WHERE timestamp_return IS NOT NULL\r\n    AND timestamp_lend IS NOT NULL\r\n) AS subquery\r\nWHERE duration_minutes < 100 AND network_name_lend::text IN ($cities)\r\nLIMIT 10000;\r\n"
    }
   ]
  },
  {
   "title": "Trip Distances ($cities)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  distance,\r\n  network_name_lend::text AS network_suffix\r\nFROM (\r\n  SELECT\r\n    (current_range_meters_lend - current_range_meters_return) / 1000 as distance,\r\n    network_name_lend,\r\n    network_name_lend::text AS network_suffix\r\n  FROM trips\r\n) AS subquery\r\nWHERE distance > 0 and distance < 10 and network_suffix IN ($cities)\r\nLIMIT 250000;"
    }
   ]
  },
  {
   "title": "Total Stations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Stations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    COUNT(DISTINCT t.station_name_id_lend) AS distinct_station_count\r\nFROM\r\n    trips t\r\nJOIN\r\n    station_names s\r\n        ON s.id = t.station_name_id_lend\r\nWHERE\r\n    t.station_name_id_lend >= 0\r\n    AND network_name_lend::text IN ($cities)\r\n    AND s.name NOT ILIKE '%bike%';\r\n"
    }
   ]
  },
  {
   "title": "Total Lends",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Lends" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(total_lends) AS total_trips\r\nFROM weekly_demand_agg wda \r\nwhere network_name::text IN ($cities)"
    }
   ]
  },
  {
   "title": "Station Locations ($cities)",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    t.station_name_id_lend,\r\n    t.location_id_lend,\r\n    ST_Y(g.location::geometry) AS latitude,\r\n    ST_X(g.location::geometry) AS longitude\r\nFROM\r\n    trips t\r\nJOIN geo_information g ON t.location_id_lend = g.location_id\r\nJOIN station_names s ON s.id = t.station_name_id_lend\r\nWHERE\r\n    t.station_name_id_lend >= 0 and network_name_lend::text IN ($cities) AND s.name NOT ILIKE '%bike%';"
    }
   ]
  }
 ]
}