{
 "title": "[GENERAL] A Year in Micromobility",
 "time": { "from": "2024-01-01T00:00:00.000Z", "to": "2024-12-31T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "cities",
    "label": "City",
    "query": "select distinct   RIGHT(network_name_lend::text, 2) from weekly_trips_agg wta;"
   },
   {
    "name": "year",
    "query": "SELECT DISTINCT EXTRACT(YEAR FROM month) AS year\nFROM monthly_trips_agg\nORDER BY year;"
   }
  ]
 },
 "panels": [
  { "title": "Statistics (All Cities)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Trips" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUM(trip_count) AS total_trips_for_year\r\nFROM daily_trips_agg\r\nWHERE EXTRACT(YEAR FROM day)::int = $year;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Returns" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    SUM(total_returns) AS total_returns_for_year\r\nFROM daily_demand_agg\r\nWHERE EXTRACT(YEAR FROM day)::int IN ($year);\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Lends" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    SUM(total_lends) AS total_lends_for_year\r\nFROM daily_demand_agg\r\nWHERE EXTRACT(YEAR FROM day)::int = $year;\r\n"
    }
   ]
  },
  {
   "title": "Cumsum of Trips",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\r\n  SELECT\r\n    day::date AS day,\r\n    network_name_lend,\r\n    SUM(trip_count) AS daily_total\r\n  FROM daily_trips_agg\r\n  WHERE EXTRACT(YEAR FROM day)::int = $year\r\n  GROUP BY day::date, network_name_lend\r\n)\r\nSELECT\r\n  day::timestamp AS time,\r\n  RIGHT(network_name_lend::text, 2) AS network_suffix,\r\n  SUM(daily_total) OVER (\r\n    PARTITION BY RIGHT(network_name_lend::text, 2)\r\n    ORDER BY day\r\n    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\r\n  ) AS \"Cumulative Trips\"\r\nFROM filtered\r\nORDER BY time, network_name_lend;\r\n"
    }
   ]
  },
  {
   "title": "Trip Distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Trips" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  RIGHT(network_name_lend::text, 2) AS network_suffix,\r\n  SUM(trip_count) AS total_trips\r\nFROM daily_trips_agg\r\nWHERE EXTRACT(YEAR FROM day)::int = $year\r\nGROUP BY RIGHT(network_name_lend::text, 2)\r\nORDER BY network_suffix;\r\n"
    }
   ]
  },
  {
   "title": "Mean Trips per Day",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    RIGHT(network_name_lend::text, 2) AS network_suffix,\r\n    SUM(trip_count) * 1.0 / COUNT(DISTINCT day) AS mean_trip_count\r\nFROM daily_trips_agg\r\nWHERE EXTRACT(YEAR FROM day)::int = $year\r\nGROUP BY RIGHT(network_name_lend::text, 2)\r\nORDER BY network_suffix;\r\n"
    }
   ]
  },
  {
   "title": "Median Trips per Day",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  network_suffix,\r\n  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY daily_total) AS median_daily_trips\r\nFROM (\r\n  SELECT\r\n    RIGHT(network_name_lend::text, 2) AS network_suffix,\r\n    day::date,\r\n    SUM(trip_count) AS daily_total\r\n  FROM daily_trips_agg\r\n  WHERE EXTRACT(YEAR FROM day)::int = $year\r\n  GROUP BY day, RIGHT(network_name_lend::text, 2)\r\n) sub\r\nGROUP BY network_suffix\r\nORDER BY network_suffix;\r\n"
    }
   ]
  },
  {
   "title": "Cumsum of Lends",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\r\n  SELECT\r\n    day::date AS day,\r\n    network_name,\r\n    SUM(total_lends) AS daily_total\r\n  FROM daily_demand_agg\r\n  WHERE EXTRACT(YEAR FROM day)::int = $year\r\n  GROUP BY day::date, network_name\r\n)\r\nSELECT\r\n  day::timestamp AS time,\r\n  RIGHT(network_name::text, 2) AS network_suffix,\r\n  SUM(daily_total) OVER (\r\n    PARTITION BY RIGHT(network_name::text, 2)\r\n    ORDER BY day\r\n    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\r\n  ) AS Cumulative_Rents\r\nFROM filtered\r\nORDER BY time, network_name;\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  RIGHT(network_name::text, 2) AS network_suffix,\r\n  SUM(total_lends) AS total_lends\r\nFROM daily_demand_agg\r\nWHERE EXTRACT(YEAR FROM day)::int = $year\r\nGROUP BY RIGHT(network_name::text, 2)\r\nORDER BY network_suffix;\r\n"
    }
   ]
  },
  {
   "title": "Cumsum of Returns",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "WITH filtered AS (\r\n  SELECT\r\n    day::date AS day,\r\n    network_name,\r\n    SUM(total_returns) AS daily_total\r\n  FROM daily_demand_agg\r\n  WHERE EXTRACT(YEAR FROM day)::int = $year\r\n  GROUP BY day::date, network_name\r\n)\r\nSELECT\r\n  day::timestamp AS time,\r\n  RIGHT(network_name::text, 2) AS network_suffix,\r\n  SUM(daily_total) OVER (\r\n    PARTITION BY RIGHT(network_name::text, 2)\r\n    ORDER BY day\r\n    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\r\n  ) AS Cumulative_Returns\r\nFROM filtered\r\nORDER BY time, network_name;\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  RIGHT(network_name::text, 2) AS network_suffix,\r\n  SUM(total_returns) AS total_returns\r\nFROM daily_demand_agg\r\nWHERE EXTRACT(YEAR FROM day)::int = $year\r\nGROUP BY RIGHT(network_name::text, 2)\r\nORDER BY network_suffix;\r\n"
    }
   ]
  }
 ]
}