{
 "title": "[GENERAL] City Descriptions",
 "time": { "from": "2023-03-31T22:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cities",
    "label": "City",
    "query": "select distinct   RIGHT(network_name_lend::text, 2) from weekly_trips_agg wta;"
   }
  ]
 },
 "panels": [
  { "title": "Statistics (All Cities)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Trips" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  TO_CHAR(DATE_TRUNC('month', day), 'YYYY-MM') AS month,\r\n  SUM(trip_count) AS total_trips\r\nFROM daily_trips_agg\r\nGROUP BY DATE_TRUNC('month', day)\r\nORDER BY DATE_TRUNC('month', day);\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Returns" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    TO_CHAR(DATE_TRUNC('month', day), 'YYYY-MM') AS month,\r\n    SUM(total_returns) AS returns\r\nFROM \r\n    daily_demand_agg\r\nGROUP BY \r\n    DATE_TRUNC('month', day)\r\nORDER BY \r\n    DATE_TRUNC('month', day);\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Lends" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    TO_CHAR(DATE_TRUNC('month', day), 'YYYY-MM') AS month,\r\n    SUM(total_lends) AS lends\r\nFROM \r\n    daily_demand_agg\r\nGROUP BY \r\n    DATE_TRUNC('month', day)\r\nORDER BY \r\n    DATE_TRUNC('month', day);\r\n"
    }
   ]
  },
  {
   "title": "Cumsum of Trips",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  day::timestamp AS time,\r\n  RIGHT(network_name_lend::text, 2) AS network_suffix,\r\n  SUM(daily_total) OVER (\r\n    PARTITION BY RIGHT(network_name_lend::text, 2)\r\n    ORDER BY day\r\n    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\r\n  ) AS \"Cumulative Trips\"\r\nFROM (\r\n  SELECT\r\n    day::date AS day,\r\n    network_name_lend,\r\n    SUM(trip_count) AS daily_total\r\n  FROM daily_trips_agg\r\n  GROUP BY day::date, network_name_lend\r\n) sub\r\nORDER BY time, network_name_lend;\r\n"
    }
   ]
  },
  {
   "title": "Trip Distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Trips" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  RIGHT(network_name_lend::text, 2) AS network_suffix,\r\n  SUM(trip_count) AS total_trips\r\nFROM daily_trips_agg\r\nGROUP BY RIGHT(network_name_lend::text, 2)\r\nORDER BY RIGHT(network_name_lend::text, 2);\r\n"
    }
   ]
  },
  {
   "title": "Mean Trips per Day",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    RIGHT(network_name_lend::text, 2) AS network_suffix,\r\n    SUM(trip_count) * 1.0 / COUNT(DISTINCT day) AS mean_trip_count\r\nFROM \r\n    daily_trips_agg\r\nGROUP BY \r\n    network_suffix\r\nORDER BY \r\n    network_suffix;\r\n"
    }
   ]
  },
  {
   "title": "Median Trips per Day",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  network_suffix,\r\n  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY daily_total) AS median_daily_trips\r\nFROM (\r\n  SELECT\r\n    RIGHT(network_name_lend::text, 2) AS network_suffix,\r\n    day::date,\r\n    SUM(trip_count) AS daily_total\r\n  FROM daily_trips_agg\r\n  GROUP BY day, RIGHT(network_name_lend::text, 2)\r\n) sub\r\nGROUP BY network_suffix\r\nORDER BY network_suffix;\r\n"
    }
   ]
  },
  {
   "title": "Cumsum of Lends",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  day::timestamp AS time,\r\n  RIGHT(network_name::text, 2) AS network_suffix,\r\n  SUM(daily_total) OVER (\r\n    PARTITION BY RIGHT(network_name::text, 2)\r\n    ORDER BY day\r\n    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\r\n  ) AS Cumulative_Rents\r\nFROM (\r\n  SELECT\r\n    day::date AS day,\r\n    network_name,\r\n    SUM(total_lends) AS daily_total\r\n  FROM daily_demand_agg \r\n  GROUP BY day::date, network_name\r\n) sub\r\nORDER BY time, network_name;\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  RIGHT(network_name::text, 2) AS network_suffix,\r\n  SUM(total_lends) AS total_lends\r\nFROM daily_demand_agg \r\nGROUP BY RIGHT(network_name::text, 2)\r\nORDER BY RIGHT(network_name::text, 2);\r\n"
    }
   ]
  },
  {
   "title": "Cumsum of Returns",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  day::timestamp AS time,\r\n  RIGHT(network_name::text, 2) AS network_suffix,\r\n  SUM(daily_total) OVER (\r\n    PARTITION BY RIGHT(network_name::text, 2)\r\n    ORDER BY day\r\n    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\r\n  ) AS Cumulative_Returns\r\nFROM (\r\n  SELECT\r\n    day::date AS day,\r\n    network_name,\r\n    SUM(total_returns) AS daily_total\r\n  FROM daily_demand_agg \r\n  GROUP BY day::date, network_name\r\n) sub\r\nORDER BY time, network_name;\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  RIGHT(network_name::text, 2) AS network_suffix,\r\n  SUM(total_returns) AS total_returns\r\nFROM daily_demand_agg \r\nGROUP BY RIGHT(network_name::text, 2)\r\nORDER BY RIGHT(network_name::text, 2);\r\n"
    }
   ]
  },
  {
   "title": "Statistics ($cities City Level)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "repeat": "cities"
  },
  {
   "title": "Total Trips",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Trips" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(trip_count) AS total_trips\r\nFROM weekly_trips_agg wta \r\nwhere RIGHT(network_name_lend::text, 2) IN ($cities)\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Total Returns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Returns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(total_returns) AS total_trips\r\nFROM weekly_demand_agg wda \r\nwhere RIGHT(network_name::text, 2) IN ($cities)"
    }
   ]
  },
  {
   "title": "Trip Durations ($cities)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  duration_minutes,\r\n  RIGHT(network_name_lend::text, 2) AS network_suffix\r\nFROM (\r\n  SELECT\r\n    FLOOR(EXTRACT(EPOCH FROM AGE(timestamp_return, timestamp_lend)) / 60) AS duration_minutes,\r\n    network_name_lend\r\n  FROM trips\r\n  WHERE timestamp_return IS NOT NULL\r\n    AND timestamp_lend IS NOT NULL\r\n) AS subquery\r\nWHERE duration_minutes < 100 AND RIGHT(network_name_lend::text, 2) IN ($cities)\r\nLIMIT 10000;\r\n"
    }
   ]
  },
  {
   "title": "Trip Distances ($cities)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  distance,\r\n  RIGHT(network_name_lend::text, 2) AS network_suffix\r\nFROM (\r\n  SELECT\r\n    (current_range_meters_lend - current_range_meters_return) / 1000 as distance,\r\n    network_name_lend,\r\n    RIGHT(network_name_lend::text, 2) AS network_suffix\r\n  FROM trips\r\n) AS subquery\r\nWHERE distance > 0 and distance < 10 and network_suffix IN ($cities)\r\nLIMIT 250000;"
    }
   ]
  },
  {
   "title": "Total Stations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Stations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    COUNT(DISTINCT t.station_name_id_lend) AS distinct_station_count\r\nFROM\r\n    trips t\r\nJOIN\r\n    station_names s\r\n        ON s.id = t.station_name_id_lend\r\nWHERE\r\n    t.station_name_id_lend >= 0\r\n    AND RIGHT(t.network_name_lend::text, 2) IN ($cities)\r\n    AND s.name NOT ILIKE '%bike%';\r\n"
    }
   ]
  },
  {
   "title": "Total Lends",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Lends" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(total_lends) AS total_trips\r\nFROM weekly_demand_agg wda \r\nwhere RIGHT(network_name::text, 2) IN ($cities)"
    }
   ]
  },
  {
   "title": "Station Locations ($cities)",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\r\n    t.station_name_id_lend,\r\n    t.location_id_lend,\r\n    ST_Y(g.location::geometry) AS latitude,\r\n    ST_X(g.location::geometry) AS longitude\r\nFROM\r\n    trips t\r\nJOIN geo_information g ON t.location_id_lend = g.location_id\r\nJOIN station_names s ON s.id = t.station_name_id_lend\r\nWHERE\r\n    t.station_name_id_lend >= 0 and RIGHT(network_name_lend::text, 2) IN ($cities) AND s.name NOT ILIKE '%bike%';"
    }
   ]
  }
 ]
}