services:
  osrm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: osrm
    environment:
      # Name of the OSM file without the .osm.pbf extension, which is used 
      # in the start-osrm.sh script to determine the input and output file paths.
      # E.g. baden-wuerttemberg-latest.osm.pbf -> baden-wuerttemberg-latest
      - OSRM_NAME=europe-latest
      # OSRM_PROFILE can be set to one of the following values: car, bike or foot.
      - OSRM_PROFILE=foot
    volumes:
      - ./data/osm/:/data:rw
    ports:
      - "5001:5000"
    networks:
      - mobility-network
 
networks:
  mobility-network:
    driver: bridge
    external: true
