services:
  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./config.yaml:/etc/loki/loki-config.yml
      - loki_data:/loki
    networks:
      - mobility-network
    ports:
      - "5006:3100"
    restart: unless-stopped

volumes:
  loki_data:

networks:
  mobility-network:
    driver: bridge
    external: true